/* * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.formulario.dao;

import Conexion.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static com.formulario.dao.formularioingreso.txtusuario;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.util.Date;
import javax.swing.JTable;

/**
 *
 * @author Steven
 */
public class formulariofactura extends javax.swing.JFrame implements Printable{
    Connection conn;
    DefaultTableModel modelo = new DefaultTableModel();
    int x=0;
    int restacant[]= new int[25];
    DateFormat df= DateFormat.getDateInstance() ;
    public formulariofactura() {
        initComponents();
        
        vendedor.setText(txtusuario.getText().toUpperCase());
        //Generar la fecha actual 
        Date FechaActual = new Date();
        dcfecha.setDate(FechaActual);
        lblfecha.setText(df.format(FechaActual));
        dcfecha.setVisible(false);
        CodigoFactura();
        Consumo(); 
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("PRECIO");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("VALOR");
        Ttabla.setModel(modelo);
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ttabla = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txtiva = new javax.swing.JTextField();
        txttotalpagar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        vendedor = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        codfactura = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bnbuscar = new javax.swing.JButton();
        dcfecha = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cbconsumo = new javax.swing.JComboBox<>();
        cbdescripcion = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        Precio1 = new javax.swing.JLabel();
        txtcantbase = new javax.swing.JTextField();
        bnguardar = new javax.swing.JButton();
        txtcantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblsalir1 = new javax.swing.JLabel();

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Ttabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Ttabla.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(Ttabla);

        jLabel17.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jLabel17.setText("Total");

        jLabel18.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jLabel18.setText("iva");

        jLabel19.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jLabel19.setText("Total a pagar");

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        jLabel1.setText("Factura ");

        vendedor.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jLabel10.setText("Cedula");

        jLabel20.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jLabel20.setText("Fecha emision");

        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });

        codfactura.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtcliente.setEditable(false);
        txtcliente.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jLabel11.setText("Cliente");

        jLabel13.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jLabel13.setText("N °");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ImgLogo.JPG"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/detalle.JPG"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/vendedor.JPG"))); // NOI18N

        bnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1472724945_Zoom.png"))); // NOI18N
        bnbuscar.setBorder(null);
        bnbuscar.setBorderPainted(false);
        bnbuscar.setContentAreaFilled(false);
        bnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addComponent(jLabel19)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(55, 55, 55)))
                        .addComponent(txttotalpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel17)
                        .addGap(17, 17, 17)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jLabel18)
                        .addGap(23, 23, 23)
                        .addComponent(txtiva, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel11)
                        .addGap(17, 17, 17)
                        .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(bnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel13)
                                .addGap(12, 12, 12)
                                .addComponent(codfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(codfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(dcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bnbuscar)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel17))
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txtiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txttotalpagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "PRODUCTOS ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 14))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jLabel14.setText("Consumo");

        cbconsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbconsumoActionPerformed(evt);
            }
        });

        cbdescripcion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbdescripcionItemStateChanged(evt);
            }
        });
        cbdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdescripcionActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jLabel15.setText("Descripcion");

        Precio.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        Precio.setText("Precio");

        jLabel16.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jLabel16.setText("Cantidad");

        txtprecio.setEditable(false);

        Precio1.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        Precio1.setText("Stock");

        txtcantbase.setEditable(false);

        bnguardar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        bnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir.png"))); // NOI18N
        bnguardar.setText("IMPRIMIR");
        bnguardar.setBorder(null);
        bnguardar.setBorderPainted(false);
        bnguardar.setContentAreaFilled(false);
        bnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bnguardar.setIconTextGap(-1);
        bnguardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir1.png"))); // NOI18N
        bnguardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir2.png"))); // NOI18N
        bnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnguardarActionPerformed(evt);
            }
        });

        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/edit_1.png"))); // NOI18N
        jButton1.setText("AGREGAR");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/edit_2.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/edit_2.png"))); // NOI18N
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(10, 10, 10)
                        .addComponent(cbconsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(4, 4, 4)
                        .addComponent(cbdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)
                        .addGap(62, 62, 62)
                        .addComponent(bnguardar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Precio)
                                .addGap(34, 34, 34)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtprecio, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(txtcantidad))
                        .addGap(52, 52, 52)
                        .addComponent(Precio1)
                        .addGap(18, 18, 18)
                        .addComponent(txtcantbase, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel14))
                    .addComponent(cbconsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel15))
                    .addComponent(cbdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantbase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Precio)
                            .addComponent(Precio1))))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        lblsalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton salir.gif"))); // NOI18N
        lblsalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblsalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsalir1MouseClicked(evt);
            }
        });
        jPanel3.add(lblsalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, 90));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 290, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          txtcedula.requestFocus();
        
    }//GEN-LAST:event_formWindowOpened

    private void cbconsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbconsumoActionPerformed
        Descripcion();
    }//GEN-LAST:event_cbconsumoActionPerformed

    private void txtcedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyReleased
       
    }//GEN-LAST:event_txtcedulaKeyReleased

    private void cbdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdescripcionActionPerformed
       Precios();     
    }//GEN-LAST:event_cbdescripcionActionPerformed

    private void bnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnguardarActionPerformed
         if(txtcedula.getText().equals("")|| txtcliente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Falta datos por ingresar","Error",JOptionPane.ERROR_MESSAGE);
            txtcedula.requestFocus();
        
        }else{
            GuardarFactura();
            DetalleFac();
            Stock();
            Imprimir();
            new menu().setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_bnguardarActionPerformed

    private void lblsalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsalir1MouseClicked
        menu.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_lblsalir1MouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int fila= Ttabla.getSelectedRow();
        Double valor=0.0d;
        if(fila>=0){
            modelo.removeRow(fila);
        }
        x--;
        Calcular();
        
    }//GEN-LAST:event_EliminarActionPerformed

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
       if(txtcedula.getText().length()==10){evt.consume();}
       char e=evt.getKeyChar();
       if(e<'0'|| e>'9'){evt.consume();}
    }//GEN-LAST:event_txtcedulaKeyTyped

    private void cbdescripcionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbdescripcionItemStateChanged
        txtcantidad.requestFocus();
    }//GEN-LAST:event_cbdescripcionItemStateChanged

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
        if(txtcantidad.getText().length()==2){evt.consume();}       
        char e=evt.getKeyChar();
        if(e<'0'|| e>'9'){evt.consume();}
        
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(txtcantidad.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese Cantidad","ERROR",JOptionPane.ERROR_MESSAGE );
        }else{
            int n= Integer.parseInt(txtcantidad.getText());
            int n2=Integer.parseInt(txtcantbase.getText());
            if(n==0){
                JOptionPane.showMessageDialog(null,"Ingrese Cantidad mayor a 0","ERROR",JOptionPane.ERROR_MESSAGE );
                txtcantidad.requestFocus();
            }else{
                if(n>n2 ){
                    JOptionPane.showMessageDialog(null, "Excede de la cantidad de stock");
                    txtcantidad.requestFocus();
                }else{
                    CargarTable();
                }
            }
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnbuscarActionPerformed
       Cliente(); 
    }//GEN-LAST:event_bnbuscarActionPerformed

    //--------- CODIGO DE LA FACTURA -------------
    public void CodigoFactura(){
        String sql="select id_factura from factura order by id_factura asc";
        try{
            conn=ConexionBD.Open();
            PreparedStatement ps= conn.prepareStatement(sql);
            ResultSet rs= ps.executeQuery();
            codfactura.setText("1");
            while(rs.next()){
                codfactura.setText(Integer.toString(rs.getInt(1)+1));  
            }
        }catch(Exception ex){
            
        } 
    }
     //------- CONSULTAR EN LA BASE DE DATOS  ---------
    public void Consumo(){
        String sql= "select * from consumo";
        try{
         Statement stm= conn.createStatement();
         ResultSet rs=stm.executeQuery(sql);
         while(rs.next()){
            cbconsumo.addItem(rs.getString(2));
         }
         cbconsumo.setSelectedIndex(-1);
        }catch(SQLException ex){
           System.out.println(ex.getMessage());
        }
        
    }
    public void Descripcion(){
        String sql="select * from productos where id_consumo1="
                +(cbconsumo.getSelectedIndex()+1);
        cbdescripcion.removeAllItems();
        try {
            Statement stm= conn.createStatement();
            ResultSet rs=stm.executeQuery(sql);
            while(rs.next()){
                cbdescripcion.addItem(rs.getString(2));
            }
            cbdescripcion.setSelectedIndex(-1);
            
        }catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
     public void Precios(){
        String sql="select cantidad,precio from productos where descripcion='"+
                cbdescripcion.getSelectedItem()+ "'";
        txtprecio.setText("");
        txtcantbase.setText("");
        try{
            Statement st= conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                txtcantbase.setText(Integer.toString(rs.getInt(1)));
                txtprecio.setText(Double.toString(rs.getDouble(2)));
            }
        
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
    }
    public void Cliente(){
        String sql = " SELECT *  FROM clientes WHERE cedula='"+txtcedula.getText()+"'";
        if(txtcedula.getText().length()<10){
            JOptionPane.showMessageDialog(null, "Digitos Incompletos","Error",JOptionPane.ERROR_MESSAGE);
            txtcedula.requestFocus();
        }else{
           try {
            Statement stm= conn.createStatement();
            ResultSet rs=stm.executeQuery(sql);
            if(rs.next()){
                this.txtcliente.setText(rs.getString(3)+"  "+rs.getString(4));
            }else{
                JOptionPane.showMessageDialog(null,"No existe en la base de dstos", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                if(JOptionPane.showConfirmDialog(null,"Ingresar Cliente", "CONFIRMAR",1)==0){
                    new formulariocliente().setVisible(true);
                    this.setVisible(false);
                }
            }
           }catch (SQLException e) {
            System.out.println(e.getMessage());
           }
        }
        
       
        if(txtcedula.getText().equals("")){ txtcliente.setText(" ");}
       
        
        
    } 
    //    --------- CARGAR TABLA ------------------
    public void CargarTable(){
        
        String []registro = new String[4];
        int cantidad = Integer.parseInt(txtcantidad.getText());
        double precio = Double.parseDouble(txtprecio.getText());
        double valor = cantidad* precio;
        registro[0] = cbdescripcion.getSelectedItem().toString();
        registro[1] = txtprecio.getText();
        registro[2] = txtcantidad.getText();
        registro[3] = Double.toString(valor);
        modelo.addRow(registro);
        Ttabla.setModel(modelo);

        Calcular();
        txtcantidad.setText("");

    }
    public int Calcular(){
        Double valor=0.0d;
        for(int c=0; c<Ttabla.getRowCount();c++){
            valor= valor+ Double.parseDouble(Ttabla.getValueAt(c, 3).toString());
        }
        Double iva = Math.rint(valor*0.14*10)/10;
       
        txttotal.setText(Double.toString(valor));
        txtiva.setText(Double.toString(iva));
        txttotalpagar.setText(Double.toString(valor+iva));   
        return x++;
    }
    
    
    public void Stock(){
       
       int fila=0;
       while(fila<x){
           try{
                String sql= "update productos set cantidad=cantidad-? where descripcion='"+
                        Ttabla.getValueAt(fila,0).toString()+"'";
                
                PreparedStatement ps= conn.prepareStatement(sql);
                ps.setInt(1, Integer.parseInt(Ttabla.getValueAt(fila,2).toString()));
                ps.execute();   
            }catch(Exception ex){
               System.out.println(ex.getMessage());
            }
                   
           fila++;
       }  
    }
    public void GuardarFactura(){
        String sql="insert into factura(fecha, cajero,cliente,valor_cancelado) values(?,?,?,?)";
        try{
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setDate(1, Convertirfecha());
            ps.setString(2, vendedor.getText());
            ps.setString(3, txtcliente.getText());
            ps.setDouble(4, Double.parseDouble(txttotalpagar.getText()));
            ps.executeUpdate();
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
    }
    public void DetalleFac(){
        String sql="insert into detallefactura(descripcion,precio,cantidad,total,factura) values(?,?,?,?,?)";
        
        int fila=0;
        while(fila<=x){
            try{
                 
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1,Ttabla.getValueAt(fila,0).toString() );
                ps.setDouble(2, Double.parseDouble(Ttabla.getValueAt(fila,1).toString()));
                ps.setInt(3, Integer.parseInt(Ttabla.getValueAt(fila,2).toString()));
                ps.setDouble(4, Double.parseDouble(Ttabla.getValueAt(fila,3).toString()));
                ps.setInt(5, Integer.parseInt(codfactura.getText()));
                ps.executeUpdate();
            }catch(Exception ex){
                
            }
            fila++;
        } 
    }
    
    public void Imprimir(){
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setPrintable(this);
        if(printerJob.printDialog()){
            try{
                printerJob.print();
            }catch(PrinterException ex){
                JOptionPane.showMessageDialog(null, "Error!", "Error\n"+ ex,JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException{
        if(pageIndex == 0){
               Graphics2D g2d = (Graphics2D) graphics;
               g2d.translate(pageFormat.getImageableX() + 30,pageFormat.getImageableY()+ 30);
               jPanel1.printAll(graphics);
               return PAGE_EXISTS;
            }else{
                 return NO_SUCH_PAGE;
             }
    }
    //------- CONVERTIDOR DE FECHA  ------------
    public java.sql.Date Convertirfecha(){
        java.sql.Date fecha = new   java.sql.Date(dcfecha.getDate().getTime());
        return fecha;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulariofactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulariofactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulariofactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulariofactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulariofactura().setVisible(true);
            }
        });
    }
//
//    public static String FechaActual(){
//        Date fecha = new Date();
//        SimpleDateFormat formato= new SimpleDateFormat("dd/MM/YYYY");
//        return formato.format(fecha); 
//    }
//    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Precio1;
    private javax.swing.JTable Ttabla;
    private javax.swing.JButton bnbuscar;
    private javax.swing.JButton bnguardar;
    public javax.swing.JComboBox<String> cbconsumo;
    public javax.swing.JComboBox<String> cbdescripcion;
    private javax.swing.JLabel codfactura;
    private javax.swing.JTextField dcfecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblsalir1;
    private javax.swing.JTextField txtcantbase;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtiva;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotalpagar;
    private javax.swing.JLabel vendedor;
    // End of variables declaration//GEN-END:variables

  
}
