/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.formulario.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Steven
 */
public class formularioingreso extends javax.swing.JFrame {
 
    Connection conn;
    
    int contador=0;
    public formularioingreso() {
        initComponents();
        //Poner el formulario en el centro
        this.setLocationRelativeTo(null);
        txtcargo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        txtcontraseña = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        bnentrar = new javax.swing.JButton();
        bnsalir = new javax.swing.JButton();
        txtusuario = new javax.swing.JTextField();
        txtcargo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INGRESO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel16.setText("Contraseña");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 102, 104, -1));

        txtcontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcontraseñaKeyTyped(evt);
            }
        });
        getContentPane().add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 102, 150, -1));

        jLabel17.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel17.setText("Usuario");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 57, 79, 25));

        bnentrar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 11)); // NOI18N
        bnentrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Boton-Entrar-Plateado.gif"))); // NOI18N
        bnentrar.setBorder(null);
        bnentrar.setBorderPainted(false);
        bnentrar.setContentAreaFilled(false);
        bnentrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bnentrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnentrarActionPerformed(evt);
            }
        });
        getContentPane().add(bnentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, 50));

        bnsalir.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 11)); // NOI18N
        bnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton salir.gif"))); // NOI18N
        bnsalir.setBorder(null);
        bnsalir.setBorderPainted(false);
        bnsalir.setContentAreaFilled(false);
        bnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(bnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 120, 70));

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 62, 150, -1));
        getContentPane().add(txtcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 30, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ImgLogin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnentrarActionPerformed
        if(txtusuario.getText().equals("")|| txtcontraseña.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Falta datos por Ingresar", "MENSAJE",JOptionPane.ERROR_MESSAGE);
            txtusuario.requestFocus();
        }else{
           Ingresar(); 
        }
        
    }//GEN-LAST:event_bnentrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        txtcontraseña.requestFocus();
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyTyped
          //Validar solo letras
        int c = evt.getKeyChar();
        if((c < 97 || c > 122) && (c< 65 || c > 90) &&  (c != 32)){
            evt.consume();
        }
    }//GEN-LAST:event_txtusuarioKeyTyped

    private void bnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bnsalirActionPerformed

    private void txtcontraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontraseñaKeyTyped
        if(txtcontraseña.getText().length()==4){evt.consume();}
    }//GEN-LAST:event_txtcontraseñaKeyTyped

    public void Limpiar(){
        txtusuario.setText("");
        txtcontraseña.setText("");
    }
    
   
    // -------------- SELECCIONAR EL APELLIDO Y CONTRASEÑA Y VERIFICAR SI ES CORRECTA O NO -------------
    public boolean Ingresar(){
        String usuario = "",contrasena="";
        boolean login= false;
        if(txtusuario.getText().equals("")|| txtcontraseña.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Falta datos por Ingresar", "MENSAJE",JOptionPane.ERROR_MESSAGE);
            
        }else{
             String sql= "SELECT apellidos,contraseña,id_carg FROM trabajador";
        
        try{
           PreparedStatement ps= conn.prepareStatement(sql);
           ResultSet rs = ps.executeQuery();
           while(rs.next()){
               usuario= rs.getString(1);
               contrasena= rs.getString(2);
               //String.valueOf convierte el valor entero en cadena 
               txtcargo.setText(String.valueOf(rs.getInt(3)));
               if((txtusuario.getText().toUpperCase().equals(usuario))&&(txtcontraseña.getText().equals(contrasena))){
                 login =true;
                 break;
               }else{
                 login =false;
               }
            }
           contador++; 
        }catch(Exception x){
           JOptionPane.showMessageDialog(null, "exception 2 "+x);
        }
        Login(login);
            
        }
       
     return login;       
    }
    public void Login(boolean login){
        if(login==true){
            JOptionPane.showMessageDialog(null,"Bienvenido:"+ txtusuario.getText().toUpperCase(),"LOGIN",JOptionPane.INFORMATION_MESSAGE);
            new menu().setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Acceso Incorrecto..", "Error",JOptionPane.ERROR_MESSAGE);
            Limpiar();
            txtusuario.requestFocus();
            if(contador==3){
                JOptionPane.showMessageDialog(null,"Intentos Fallidos,Espere 15s.","Error", JOptionPane.ERROR_MESSAGE);
                try{
                   Limpiar();
                   Thread.sleep(18000);
                   Limpiar();
                   txtusuario.requestFocus();
                }catch(Exception ex){}
                contador=0;
            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnentrar;
    private javax.swing.JButton bnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    public static javax.swing.JTextField txtcargo;
    private javax.swing.JPasswordField txtcontraseña;
    public static javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
